"""empty message

Revision ID: 3d5aadf39207
Revises: 82186ef753b0
Create Date: 2020-11-17 15:38:10.482924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5aadf39207'
down_revision = '82186ef753b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transaction', 'student', ['student_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'treasure_item', ['treasure_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    # ### end Alembic commands ###
